name: Preview (within a pull request)
on:
  pull_request:
    branches:
      - dev
      - main
      - 'dev-patch'
      - 'patch-*'
    types: [opened, edited, synchronize, reopened]
jobs:
  name: Analyze
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: sonarsource/sonarqube-scan-action@v3
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    - uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          check-latest: true
      - name: Check Node version
        run: node -v
      - name: Update NPM version
        run: npm install -g "npm@^7.6.3"
      - name: Install
        run: npm ci
      - name: Test
        run: npm test
      - name: Coverage
        uses: codecov/codecov-action@v4
      - name: Build Docs
        run: npm run build:docs
      - name: Build Storybook
        run: npm run build:storybook
      - name: Deploy Documentation Preview to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './website/react-magma-docs/public'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: false
          alias: docs-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Deploy Storybook to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './storybook-static'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: false
          alias: storybook-preview-${{ github.event.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
